version: '3.8'

services:
  kovcheg:
    build: .
    image: kovcheg-engine:latest
    container_name: kovcheg_core
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./sources:/app/sources
      - ./models_cache:/app/models_cache
      - kovcheg_config:/root/.kovcheg 
    environment:
      - LOG_LEVEL=info

volumes:
  kovcheg_models:
  kovcheg_config: 
